// Automatically generated by generate_sitemap.py. Do not edit manually.
window.SITEMAP_DATA = {
  "generatedAt": "2026-07-23T11:21:39+00:00",
  "pageCount": 28,
  "moduleCount": 8,
  "brokenLinkCount": 0,
  "modules": [
    {
      "name": "Home",
      "pages": [
        {
          "path": "homepage/homepage.html",
          "url": "../homepage/homepage.html",
          "title": "Home - Rshop",
          "heading": "Welcome to Rshop",
          "description": "",
          "module": "Home",
          "type": "page",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "shopping_cart/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "shopping_cart/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Start Shopping",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Join Discussion",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "🛒 Marketplace Browse products",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "💬 Forum Join discussions",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "📝 Blog Read articles",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "⭐ Reviews Rate products",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "❤️ Wishlist Save favorites",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "👤 Profile Manage account",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Create Account",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Shop",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            }
          ]
        }
      ]
    },
    {
      "name": "Marketplace & Shopping",
      "pages": [
        {
          "path": "shopping_cart/auth.html",
          "url": "../shopping_cart/auth.html",
          "title": "Login / Sign Up - Furniture Request Marketplace",
          "heading": "Enter your login or credentials!",
          "description": "",
          "module": "Marketplace & Shopping",
          "type": "account",
          "links": []
        },
        {
          "path": "shopping_cart/cart.html",
          "url": "../shopping_cart/cart.html",
          "title": "Shopping Cart",
          "heading": "Wishlist Cart",
          "description": "Review items moved from wishlist before checkout.",
          "module": "Marketplace & Shopping",
          "type": "page",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "â† Back to Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Proceed to Checkout",
              "target": "shopping_cart/checkout.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "shopping_cart/checkout.html",
          "url": "../shopping_cart/checkout.html",
          "title": "Checkout - Wishlist Cart",
          "heading": "Secure Checkout",
          "description": "",
          "module": "Marketplace & Shopping",
          "type": "action",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "â† Back to Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "shopping_cart/order-confirmation.html",
          "url": "../shopping_cart/order-confirmation.html",
          "title": "Order Confirmation",
          "heading": "Order Confirmed",
          "description": "",
          "module": "Marketplace & Shopping",
          "type": "page",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Back to Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Continue Browsing Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "shopping_cart/products.html",
          "url": "../shopping_cart/products.html",
          "title": "Main Market - Custom Makers Marketplace",
          "heading": "🏪 Custom Makers Main Market",
          "description": "",
          "module": "Marketplace & Shopping",
          "type": "page",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "📋 Browse All Threads",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "📝 Post New Request",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "❤️ My Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "🛒 See your Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "View Discussion",
              "target": "discuss_forum/thread-detail.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Make Offer",
              "target": "discuss_forum/thread-detail.html",
              "fragment": "reply-form",
              "exists": true
            },
            {
              "text": "Read Article",
              "target": "Blog/blog-detail.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Browse Latest Reviews",
              "target": "Product_Review_Rating/review.html",
              "fragment": "reviews",
              "exists": true
            },
            {
              "text": "Write a New Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "create-review",
              "exists": true
            },
            {
              "text": "Open Review Center",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "shopping_cart/profile.html",
          "url": "../shopping_cart/profile.html",
          "title": "User Profile",
          "heading": "Loading...",
          "description": "",
          "module": "Marketplace & Shopping",
          "type": "account",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            }
          ]
        }
      ]
    },
    {
      "name": "Reviews & Ratings",
      "pages": [
        {
          "path": "Product_Review_Rating/review.html",
          "url": "../Product_Review_Rating/review.html",
          "title": "WebReview - Website Review Platform",
          "heading": "WebReview - Website Review Platform",
          "description": "",
          "module": "Reviews & Ratings",
          "type": "page",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Read Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Go to Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            }
          ]
        }
      ]
    },
    {
      "name": "Blog",
      "pages": [
        {
          "path": "Blog/auth.html",
          "url": "../Blog/auth.html",
          "title": "Login / Sign Up - Furniture Request Marketplace",
          "heading": "ðŸ›‹ï¸ Furniture Marketplace",
          "description": "",
          "module": "Blog",
          "type": "account",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "Blog/blog-create.html",
          "url": "../Blog/blog-create.html",
          "title": "Create Blog Post - WebReview",
          "heading": "Create a New Blog Post",
          "description": "",
          "module": "Blog",
          "type": "action",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cancel",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog list",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Create post",
              "target": "Blog/blog-create.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "Blog/blog-detail.html",
          "url": "../Blog/blog-detail.html",
          "title": "Đánh giá UX của Shopee Việt Nam - WebReview Blog",
          "heading": "Đánh giá UX của Shopee Việt Nam / Shopee Vietnam UX Review",
          "description": "Full blog post: Shopee Vietnam UX review by Nguyễn Minh An.",
          "module": "Blog",
          "type": "content",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "← Back to all posts",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Edit post",
              "target": "Blog/blog-edit.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Back to list",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog list",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Create post",
              "target": "Blog/blog-create.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "Blog/blog-edit.html",
          "url": "../Blog/blog-edit.html",
          "title": "Edit Blog Post - WebReview",
          "heading": "Edit Blog Post",
          "description": "",
          "module": "Blog",
          "type": "action",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cancel",
              "target": "Blog/blog-detail.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog list",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Create post",
              "target": "Blog/blog-create.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "Blog/blog-list.html",
          "url": "../Blog/blog-list.html",
          "title": "Blog List - WebReview",
          "heading": "Latest Blog Posts",
          "description": "Browse website reviews, UX insights, and community blog posts on WebReview.",
          "module": "Blog",
          "type": "page",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Reset",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "View all posts",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Create new post",
              "target": "Blog/blog-create.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "UX",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Accessibility",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Performance",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "E-commerce",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Đánh giá UX của Shopee Việt Nam / Shopee Vietnam UX Review",
              "target": "Blog/blog-detail.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Read full post",
              "target": "Blog/blog-detail.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Edit",
              "target": "Blog/blog-edit.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Building Accessible Web Forms That Actually Work",
              "target": "Blog/blog-detail.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Tối ưu hiệu năng website thương mại điện tử",
              "target": "Blog/blog-detail.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Coursera vs. Local EdTech: A Design Comparison",
              "target": "Blog/blog-detail.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog list",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Create post",
              "target": "Blog/blog-create.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Admin",
              "target": "admin/login.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "Blog/blogpage.html",
          "url": "../Blog/blogpage.html",
          "title": "Blog - WebReview",
          "heading": "Blog - WebReview",
          "description": "",
          "module": "Blog",
          "type": "page",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog list",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "Blog/profile.html",
          "url": "../Blog/profile.html",
          "title": "User Profile",
          "heading": "Loading...",
          "description": "",
          "module": "Blog",
          "type": "account",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            }
          ]
        }
      ]
    },
    {
      "name": "Discussion Forum",
      "pages": [
        {
          "path": "discuss_forum/create-thread.html",
          "url": "../discuss_forum/create-thread.html",
          "title": "Edit Request - Custom Makers Marketplace",
          "heading": "Edit Your Request",
          "description": "Edit the details of your custom-make request.",
          "module": "Discussion Forum",
          "type": "action",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cancel",
              "target": "discuss_forum/thread-detail.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "discuss_forum/edit-post.html",
          "url": "../discuss_forum/edit-post.html",
          "title": "Edit Request - Custom Makers Marketplace",
          "heading": "Edit Your Request",
          "description": "Edit the details of your custom-make request.",
          "module": "Discussion Forum",
          "type": "action",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cancel",
              "target": "discuss_forum/thread-detail.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "discuss_forum/edit-reply.html",
          "url": "../discuss_forum/edit-reply.html",
          "title": "Edit Reply - Custom Makers Marketplace",
          "heading": "Edit Your Reply",
          "description": "Edit your reply or offer on a custom-make request.",
          "module": "Discussion Forum",
          "type": "action",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cancel",
              "target": "discuss_forum/thread-detail.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "discuss_forum/forum.html",
          "url": "../discuss_forum/forum.html",
          "title": "Request Board - Custom Makers Marketplace",
          "heading": "Custom Makers Request Board",
          "description": "Browse open custom-make requests posted by the community.",
          "module": "Discussion Forum",
          "type": "page",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Need a custom ergonomic wooden desk",
              "target": "discuss_forum/thread-detail.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "discuss_forum/thread-detail.html",
          "url": "../discuss_forum/thread-detail.html",
          "title": "Request Details - Custom Makers Marketplace",
          "heading": "Need a custom ergonomic wooden desk",
          "description": "View request details, replies, and offers, or agree a price with a maker.",
          "module": "Discussion Forum",
          "type": "content",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Edit Request",
              "target": "discuss_forum/edit-post.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Edit Reply",
              "target": "discuss_forum/edit-reply.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "discuss_forum/wishlist.html",
          "url": "../discuss_forum/wishlist.html",
          "title": "My Wishlist - Custom Makers Marketplace",
          "heading": "My Saved Wishlist Items",
          "description": "View and manage the custom requests and products you have saved.",
          "module": "Discussion Forum",
          "type": "page",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Need a custom ergonomic wooden desk",
              "target": "discuss_forum/thread-detail.html",
              "fragment": "",
              "exists": true
            }
          ]
        }
      ]
    },
    {
      "name": "User Account",
      "pages": [
        {
          "path": "user_account/auth.html",
          "url": "../user_account/auth.html",
          "title": "Authentication - Service Marketplace",
          "heading": "Welcome Back",
          "description": "",
          "module": "User Account",
          "type": "account",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "user_account/profile.html",
          "url": "../user_account/profile.html",
          "title": "User Profile",
          "heading": "Loading...",
          "description": "",
          "module": "User Account",
          "type": "account",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            }
          ]
        }
      ]
    },
    {
      "name": "Administration",
      "pages": [
        {
          "path": "admin/dashboard.html",
          "url": "../admin/dashboard.html",
          "title": "Admin Dashboard - WebReview",
          "heading": "Admin Dashboard",
          "description": "",
          "module": "Administration",
          "type": "administration",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Dashboard",
              "target": "admin/dashboard.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "User management",
              "target": "admin/users.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "My profile",
              "target": "admin/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog module",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign out",
              "target": "admin/login.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "👥 Manage users",
              "target": "admin/users.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "✏️ New blog post",
              "target": "Blog/blog-create.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "📋‹ View all posts",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "⚙️ Admin profile",
              "target": "admin/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Users",
              "target": "admin/users.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "admin/profile.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "admin/login.html",
          "url": "../admin/login.html",
          "title": "Admin Login - WebReview",
          "heading": "WebReview Admin",
          "description": "",
          "module": "Administration",
          "type": "account",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forgot password?",
              "target": "admin/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Back to Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "admin/profile.html",
          "url": "../admin/profile.html",
          "title": "Admin Profile - WebReview",
          "heading": "My Profile",
          "description": "",
          "module": "Administration",
          "type": "account",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Dashboard",
              "target": "admin/dashboard.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "User management",
              "target": "admin/users.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "My profile",
              "target": "admin/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog module",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign out",
              "target": "admin/login.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Users",
              "target": "admin/users.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "admin/profile.html",
              "fragment": "",
              "exists": true
            }
          ]
        },
        {
          "path": "admin/users.html",
          "url": "../admin/users.html",
          "title": "User Management - WebReview Admin",
          "heading": "User Management",
          "description": "",
          "module": "Administration",
          "type": "administration",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Dashboard",
              "target": "admin/dashboard.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "User management",
              "target": "admin/users.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "My profile",
              "target": "admin/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog module",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign out",
              "target": "admin/login.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Reset",
              "target": "admin/users.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "View",
              "target": "admin/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Users",
              "target": "admin/users.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "admin/profile.html",
              "fragment": "",
              "exists": true
            }
          ]
        }
      ]
    },
    {
      "name": "Shared Pages",
      "pages": [
        {
          "path": "sitemap/sitemap.html",
          "url": "../sitemap/sitemap.html",
          "title": "HTML Sitemap - Rshop",
          "heading": "Website Sitemap",
          "description": "Automatically generated overview of all public pages, modules, forum threads, and blog content on Rshop.",
          "module": "Shared Pages",
          "type": "page",
          "links": [
            {
              "text": "🛒",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Rshop",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Home",
              "target": "homepage/homepage.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Market",
              "target": "shopping_cart/products.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Blog",
              "target": "Blog/blog-list.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Forum",
              "target": "discuss_forum/forum.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Wishlist",
              "target": "discuss_forum/wishlist.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Cart",
              "target": "shopping_cart/cart.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Review",
              "target": "Product_Review_Rating/review.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Post",
              "target": "discuss_forum/create-thread.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Profile",
              "target": "user_account/profile.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sitemap",
              "target": "sitemap/sitemap.html",
              "fragment": "",
              "exists": true
            },
            {
              "text": "Sign In",
              "target": "user_account/auth.html",
              "fragment": "",
              "exists": true
            }
          ]
        }
      ]
    }
  ],
  "brokenLinks": []
};
